FROM opensuse:42.2
#RUN zypper --non-interactive in --force-resolution krb5
RUN zypper --non-interactive dup
RUN zypper --non-interactive in --force-resolution calligra-words
CMD /usr/bin/calligrawords
